version = 1

# Встроенный анализатор JS/TS
[[analyzers]]
name = "javascript"
enabled = true

# Кастомный анализатор для ESLint
[[analyzers]]
type = "custom"
name = "eslint-lint"
enabled = true
[analyzers.meta]
cmd = "npm run lint"
