version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  # если у вас TypeScript
  environment = ["browser", "nodejs", "typescript"]
  # какой конфиг ESLint использовать (опционально)
  config_file = ".eslintrc.json"
  # какую команду запускать перед линтингом (если нужно)
  setup_command = "npm install"